[[songs]]
id = 1
name = "Happy Birthday"
url = "https://drive.google.com/uc?export=download&id=1gPFrMz4tngMJXhUYpp57IYhtSBazbVOY"

[[songs]]
id = 2
name = "Happy Birthday (Version Reggaeton)"
url = "https://drive.google.com/uc?export=download&id=1WwdF27hy78eMfDUyN5SQyuHDgTRAu18J"

[[songs]]
id = 3
name = "Thalía - Quinceañera"
url = "https://drive.google.com/uc?export=download&id=1kXnZMKiodKmDziQ7brWLmad6QSPt0FZ-"

[[songs]]
id = 4
name = "Vicente Fernandez - Las Mañanitas"
url = "https://drive.google.com/uc?export=download&id=1bTbebUhXA6kEVHxd47LU6gZpic0AzVla"

[[songs]]
id = 5
name = "Ismael Gallegos - En Tu Día"
url = "https://drive.google.com/uc?export=download&id=11N0NzSr8t6bMVYZgFfq2RR2yzY9rMfvZ"